Repository kakao-tech-campus-3rd-step3/Team8_BE, pull requests merged in 2025-09, with the labels that each got.

#32 [develop ← feature/download-stream] 🚀 File Naming 변경 및 Password Encoder 적용
  build.gradle
  src/main/java/com/kakaotechcampus/journey_planner/application/auth/AuthService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/auth/utils/PasswordEncodeUtil.java
  src/main/java/com/kakaotechcampus/journey_planner/application/memo/MemoService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/plan/PlanService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/route/RouteService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/waypoint/WaypointService.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/member/Member.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/memo/MemoMapper.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/waypoint/WaypointMapper.java
  src/main/java/com/kakaotechcampus/journey_planner/global/config/PasswordEncoderConfig.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/auth/AuthController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/auth/dto/request/LoginRequestDto.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/auth/dto/request/SignUpRequestDto.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/auth/dto/response/TokenResponseDto.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/dto/PlanResponse.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/dto/auth/TokenResponse.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/memo/MemoController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/memo/dto/request/MemoRequest.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/memo/dto/response/MemoResponse.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/PlanController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/dto/request/CreatePlanRequest.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/dto/request/UpdatePlanRequest.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/dto/response/PlanResponse.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/route/RouteController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/route/dto/request/RouteRequest.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/route/dto/response/RouteResponse.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/waypoint/WaypointController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/waypoint/dto/request/WaypointRequest.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/waypoint/dto/response/WaypointResponse.java
Labels: ✨FEATURE

#49 🧩[develop ← feature/active-test] 실제 동작 테스트 코드 리팩토링
  src/main/resources/static/active-test.html
Labels: 🔨REFACTOR

#53 ❗️[develop ← feature/websocket-api-docs] 문서 생성 버그 수정
  .github/workflows/deploy.yaml
Labels: 🕷BUG

#68 [develop ← feature/kafka-adoption] CORS 설정 수정
  src/main/java/com/kakaotechcampus/journey_planner/global/config/WebMvcConfig.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/PlanController.java
Labels: ✨FEATURE

#69 [develop ← feature/kafka-adoption] Member 에 따른 Plan 전체 불러오기 기능 + Cors 수정
  src/main/java/com/kakaotechcampus/journey_planner/application/plan/PlanService.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/plan/Plan.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/plan/PlanRepository.java
  src/main/java/com/kakaotechcampus/journey_planner/global/config/WebMvcConfig.java
  src/main/java/com/kakaotechcampus/journey_planner/global/resolver/LoginMemberArgumentResolver.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/PlanController.java
Labels: ✨FEATURE, 🎺ENHANCEMENT

#73 ❗️[develop ← feature/auth-password-verification] 로그인 실패 문제 수정
  src/main/java/com/kakaotechcampus/journey_planner/application/auth/AuthService.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/member/Member.java
Labels: 🕷BUG

#78 [develop ← feature/kafka-adoption] DockerFile 작성 및 컴파일오류 해결
  .env.db.template
  .env.server.template
  .gitignore
  docker-compose.yaml
  mysql.dockerfile
  springboot.dockerfile
  src/main/java/com/kakaotechcampus/journey_planner/application/pdf/PdfService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/plan/PlanService.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/plan/PlanMapper.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/plan/PlanRepository.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/PlanController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/dto/response/PlanResponse.java
  src/main/resources/WEB-INF/templates/PdfTemplate.html
  src/main/resources/WEB-INF/templates/PdfTemplate2.html
  src/main/resources/WEB-INF/templates/PdfTemplate3.html
Labels: ✨FEATURE

#80 [develop ← feature/pdf] 동일 기능 파일 한 파일로 응축
  src/main/java/com/kakaotechcampus/journey_planner/global/config/WebConfig.java
  src/main/java/com/kakaotechcampus/journey_planner/global/config/WebMvcConfig.java
Labels: ✨FEATURE
