Repository kakao-tech-campus-3rd-step3/Team8_BE, pull requests merged in 2025-10, with the labels that each got.

#81 🔨[develop ← feature/traveler-api] Traveler API 개발
  src/main/java/com/kakaotechcampus/journey_planner/application/member/MemberService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/memberplan/MemberPlanService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/plan/PlanService.java
  src/main/java/com/kakaotechcampus/journey_planner/application/traveler/TravelerService.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/member/Member.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/memberplan/MemberPlan.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/memberplan/MemberPlanMapper.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/memberplan/MemberPlanRepository.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/plan/Plan.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/plan/PlanMapper.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/plan/PlanRepository.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/traveler/InvitationStatus.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/traveler/Role.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/traveler/Traveler.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/traveler/TravelerMapper.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/traveler/TravelerRepository.java
  src/main/java/com/kakaotechcampus/journey_planner/global/exception/ErrorCode.java
  src/main/java/com/kakaotechcampus/journey_planner/global/resolver/LoginMemberArgumentResolver.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/PlanController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/dto/response/InvitationResponse.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/dto/response/PlanResponse.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/traveler/TravelerController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/traveler/dto/response/TravelerResponse.java
Labels: ✨FEATURE

#95 [develop ← feature/admin-logic-separate] 🚀 Message Util 리팩토링 및 라즈베리파이 IP 등록
  src/main/java/com/kakaotechcampus/journey_planner/application/message/MessageService.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/message/MessageBehaviorType.java
  src/main/java/com/kakaotechcampus/journey_planner/domain/message/MessageType.java
  src/main/java/com/kakaotechcampus/journey_planner/global/config/WebMvcConfig.java
  src/main/java/com/kakaotechcampus/journey_planner/infra/message/MessageProvider.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/memo/MemoController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/plan/PlanController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/route/RouteController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/support/PdfResponseFactory.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/traveler/TravelerController.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/utils/MessagingUtil.java
  src/main/java/com/kakaotechcampus/journey_planner/presentation/waypoint/WaypointController.java
Labels: 🔨REFACTOR, ✨FEATURE

#96 [develop ← feature/admin-logic-separate] 🔨 MessageUtil 삭제 후, Subscribe 되지 않는 오류 수정
  src/main/java/com/kakaotechcampus/journey_planner/infra/message/MessageProvider.java
  src/main/resources/static/active-test.html
Labels: 🕷BUG
